<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE personas [
        <!ELEMENT personas (persona*)>
        <!ELEMENT persona (nombre, fecha_nacimiento, ciudad)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT fecha_nacimiento (dia, mes, año)>
        <!ELEMENT dia (#PCDATA)>
        <!ELEMENT mes (#PCDATA)>
        <!ELEMENT año (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
        ]>

<personas>
    <persona>
        <nombre>Pablo</nombre>
        <fecha_nacimiento>
            <dia>24</dia>
            <mes>12</mes>
            <año>1999</año>
        </fecha_nacimiento>
        <ciudad>Valencia</ciudad>
    </persona>
</personas>